version: "3.9"

services:
  backend:
    image: minha512/ai-doctor_backend:latest
    container_name: ai-doctor_backend_service
    volumes:
      - /data/Weights:/back/Weights
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - vllm
    environment:
      - REDIS_HOST=redis
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  frontend:
    image: minha512/ai-doctor_frontend:latest
    container_name: ai-doctor_frontend_service
    restart: unless-stopped
    ports:
      - "80:80"

  redis:
    image: redis:latest
    restart: unless-stopped

  vllm:
    image: vllm/vllm-openai:latest
    ports:
      - "8001:8000"
    volumes:
      - /data/Models:/models
    command: >
      --model /models/hari-q3-8b-awq
      --host 0.0.0.0
      --port 8000
      --gpu-memory-utilization 0.86
      --max-model-len 1024
      --max-num-seqs 1
      --max-num-batched-tokens 1024
      --enforce-eager
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]